#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# orp documentation build configuration file, created by
# sphinx-quickstart on Fri Oct  6 12:48:16 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

from datetime import datetime
extensions = []
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

# General information about the project.
project = 'ORP'
copyright = str(datetime.now().year)
author = u'%d Adam Allevato' % datetime.now().year

version = '1.0'
release = '1.0.0'

exclude_patterns = ['_build']

html_theme = 'alabaster'
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}
html_theme_options = {
    'description': "Object Recognition and Pose Perception",
    'fixed_sidebar': False
}